apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactjs
  template:
    metadata:
      labels:
        app: reactjs  
    spec:
      containers: 
      - name: weather-app
        image: safat661/learning
        ports:
        - containerPort: 3000